steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      - .
    timeout: 180s

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=K8s_configs/deployment-v1.yaml'
      - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      - '--location=us-central1'
      - '--cluster=applied-well-406512-gke-cluster'
      - '--command=pm2-runtime start app.js --name my-app'

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=K8s_configs/deployment-v2.yaml'
      - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      - '--location=us-central1'
      - '--cluster=applied-well-406512-gke-cluster'
      - '--command=pm2-runtime start app2.js --name my-app2'



  # - name: gcr.io/cloud-builders/gke-deploy
  #   args:
  #     - run
  #     - '--filename=K8s_configs/deployment-v2.yaml'  # Specify the deployment file for v2
  #     - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'
  #     - '--location=us-central1'
  #     - '--cluster=applied-well-406512-gke-cluster'
      
options:
  logging: CLOUD_LOGGING_ONLY
