steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nth-glass-406611/myapp:v1', '.']
    timeout: '180s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nth-glass-406611/myapp:v1']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nth-glass-406611/myapp:v2', '-f', 'Dockerfile2', '.']
    timeout: '180s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nth-glass-406611/myapp:v2']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: ['run', '--filename=K8s_configs/deployment-v1.yaml', '--image=gcr.io/nth-glass-406611/myapp:v1', '--location=us-central1', '--cluster=nth-glass-406611-gke']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: ['run', '--filename=K8s_configs/deployment-v2.yaml', '--image=gcr.io/nth-glass-406611/myapp:v2', '--location=us-central1', '--cluster=nth-glass-406611-gke']

options:
  logging: CLOUD_LOGGING_ONLY



  # - name: gcr.io/cloud-builders/gke-deploy
  #   args:
  #     - run
  #     - '--filename=K8s_configs/deployment-v2.yaml'  # Specify the deployment file for v2
  #     - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'
  #     - '--location=us-central1'
  #     - '--cluster=applied-well-406512-gke-cluster'
      
# options:
#   logging: CLOUD_LOGGING_ONLY
