steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      - .
    timeout: 180s

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'
      - -f
      - 'Dockerfile2'
      - .
    timeout: 180s

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=K8s_configs/deployment-v1.yaml'  # Specify the deployment file for v1
      - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      - '--location=us-central1'
      - '--cluster=applied-well-406512-gke-cluster'

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=K8s_configs/deployment-v2.yaml'  # Specify the deployment file for v2
      - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'
      - '--location=us-central1'
      - '--cluster=applied-well-406512-gke-cluster'
      
options:
  logging: CLOUD_LOGGING_ONLY

# steps:
#   - name: gcr.io/cloud-builders/docker
#     args:
#       - build
#       - '-t'
#       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
#       - .
#     timeout: 180s

#   - name: gcr.io/cloud-builders/docker
#     args:
#       - build
#       - '-t'
#       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'  # New image tag for Dockerfile2
#       - -f
#       - 'Dockerfile2'  # Specify Dockerfile2
#       - .
#     timeout: 180s

#   - name: gcr.io/cloud-builders/docker
#     args:
#       - push
#       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
      
#   - name: gcr.io/cloud-builders/docker
#     args:
#       - push
#       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v2'  # Push the new image

#   - name: gcr.io/cloud-builders/gke-deploy
#     args:
#       - run
#       - '--filename=K8s_configs/'
#       - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
#       - '--location=us-central1'
#       - '--cluster=applied-well-406512-gke-cluster'
      
# options:
#   logging: CLOUD_LOGGING_ONLY

# # steps:
# #   - name: gcr.io/cloud-builders/docker
# #     args:
# #       - build
# #       - '-t'
# #       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
# #       - .
# #     timeout: 180s
# #   - name: gcr.io/cloud-builders/docker
# #     args:
# #       - push
# #       - 'us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
# #   - name: gcr.io/cloud-builders/gke-deploy
# #     args:
# #       - run
# #       - '--filename=K8s_configs/'
# #       - '--image=us-docker.pkg.dev/applied-well-406512/docker/myapp:v1'
# #       - '--location=us-central1'
# #       - '--cluster=applied-well-406512-gke-cluster'
# # options:
# #   logging: CLOUD_LOGGING_ONLY
