apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
      - name: nlp-app
        image: gcr.io/nth-glass-406611/myapp:v1
        ports:
        - containerPort: 3005
        volumeMounts:
        - name: pvc-demo-vol
          mountPath: /var/log/myapp        
      imagePullSecrets:
      - name: gcr-secret
      revisionHistoryLimit: 3
  volumes:
    - name: pvc-demo-vol
      persistentVolumeClaim:
       claimName: pvc-demo
