apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
        - name: nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3005
          readinessProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 2  
          
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3005
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 3005
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
      imagePullSecrets:
        - name: gcr-secret
