apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
        - name: nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3005
          volumeMounts:
            - name: js-volume
              mountPath: /app
              subPath: script.js
      imagePullSecrets:
        - name: gcr-secret
      volumes:
        - name: js-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gcp-secret-provider


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: another-sentimentanalysis
  template:
    metadata:
      labels:
        app: another-sentimentanalysis
    spec:
      containers:
        - name: another-nlp-app
          image: gcr.io/nth-glass-406611/myapp:v2
          ports:
            - containerPort: 4005  # Update to match the port used by your second app
      imagePullSecrets:
        - name: gcr-secret
