apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
        - name: nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3005
          readinessProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /
              port: 3005
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2  
          volumeMounts:
            - mountPath: /var/lib/www/html  # Adjust the mount path based on your container's requirements
              name: mypvc
      imagePullSecrets:
        - name: gcr-secret
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: pvc-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: another-sentimentanalysis
  template:
    metadata:
      labels:
        app: another-sentimentanalysis
    spec:
      containers:
        - name: another-nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3006  # Update to match the port used by your second app
      imagePullSecrets:
        - name: gcr-secret
