---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
        - name: nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3005
          # volumeMounts:
          #   - mountPath: /var/lib/www/html
          #     name: models-1-0-0
      imagePullSecrets:
        - name: gcr-secret
    # volumes:
    #   - name: models-1-0-0
    #     persistentVolumeClaim:
    #       claimName: models-1-0-0-claim
    #       readOnly: false
