apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sentimentanalysis
  template:
    metadata:
      labels:
        app: sentimentanalysis
    spec:
      containers:
        - name: nlp-app
          image: gcr.io/nth-glass-406611/myapp:v1
          ports:
            - containerPort: 3005
          readinessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: gcr-secret
