apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: pavan2.juno.fi
      http:
        paths:
          - path: /
            backend:
              service:
                name: sentimentanalysis
                port:
                  number: 80
            pathType: Prefix
    # - host: pavan3.juno.fi
    #   http:
    #     paths:
    #       - path: /
    #         backend:
    #           service:
    #             name: sentimentanalysis-3006
    #             port:
    #               number: 80
    #         pathType: Prefix
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: nginx
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - image: nginx
#         name: nginx
#         ports:
#         - containerPort: 80
