apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
spec:
  rules:
  - host: "dev.api.juno.fi"
    http:
      paths:
      - backend:
          service:
            name: sentimentanalysis
            port:
              number: 80
  - host: "dev.app.juno.fi"
    http:
      paths:
      - backend:
          service:
            name: sentimentanalysis
            port:
              number: 80
  - host: "dev.juno.fi"
    http:
      paths:
      - backend:
          service:
            name: sentimentanalysis
            port:
              number: 80
