# # PersistentVolume for application logs
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: app-logs-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /mnt/app-logs
---
# PersistentVolumeClaim for application logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
  # hostPath:
  #   path: /mnt/app-logs  


# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fluentd-elasticsearch-pvc
#   labels:
#     app: fluentd-logging
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi 
