apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
  namespace: default
spec:
  provider: gcp


# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: secret-provider
#   namespace: playground
# spec:
#   provider: gcp
#   parameters:
#     secrets: |
#       - resourceName: "projects/<project-id>/secrets/<secret-id>/versions/latest"
#         fileName: "secret.data"
#   secretObjects:
#     - data:
#         - key: client_secret
#           objectName: "secret.data"
#       secretName: <wished-secret-name-in-k8s-secrets>
#       type: Opaque
