apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis
spec:
  type: NodePort
  selector:
    app: sentimentanalysis
  ports:
  - port: 80
    targetPort: 3005

---
apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis-3006
spec:
  type: NodePort
  selector:
    app: sentimentanalysis-3006
  ports:
  - port: 80
    targetPort: 3006
