apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis
spec:
  type: NodePort  # Changed to NodePort
  selector:
    app: sentimentanalysis
  ports:
  - port: 80
    targetPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: another-sentimentanalysis
spec:
  type: NodePort
  selector:
    app: another-sentimentanalysis  # Update this selector according to your app.js labels
  ports:
  - port: 80  # Use any available port you prefer
    targetPort: 3006  # Update this to match the port used by your second app
