apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis
spec:
  type: NodePort
  selector:
    app: sentimentanalysis
  ports:
  - port: 3005
    targetPort: 3005
    nodePort: 30005  # Choose a port within the allowed range
---
apiVersion: v1
kind: Service
metadata:
  name: sentimentanalysis-3006
spec:
  type: NodePort
  selector:
    app: sentimentanalysis-3006
  ports:
  - port: 3006
    targetPort: 3006
    nodePort: 30006  # Choose a port within the allowed range
